import React from 'react';
export type IconProps = React.SVGProps<SVGSVGElement> & {
  size?: number | string;
  strokeWidth?: number | string;
};
export type LucideIcon = React.ForwardRefExoticComponent<IconProps & React.RefAttributes<SVGSVGElement>>;

export { ArrowDown } from './ArrowDown';
export { ArrowLeft } from './ArrowLeft';
export { ArrowRight } from './ArrowRight';
export { ArrowUpRight } from './ArrowUpRight';
export { BadgeCheck } from './BadgeCheck';
export { BadgeDollarSign } from './BadgeDollarSign';
export { BookOpen } from './BookOpen';
export { Briefcase } from './Briefcase';
export { Building2 } from './Building2';
export { Calendar } from './Calendar';
export { Check } from './Check';
export { CheckCircle2 } from './CheckCircle2';
export { ChevronDown } from './ChevronDown';
export { ChevronRight } from './ChevronRight';
export { ChevronUp } from './ChevronUp';
export { CircleDollarSign } from './CircleDollarSign';
export { Clock } from './Clock';
export { Cpu } from './Cpu';
export { CreditCard } from './CreditCard';
export { Download } from './Download';
export { ExternalLink } from './ExternalLink';
export { FileText } from './FileText';
export { Globe } from './Globe';
export { GraduationCap } from './GraduationCap';
export { Handshake } from './Handshake';
export { Headphones } from './Headphones';
export { HelpCircle } from './HelpCircle';
export { Layers } from './Layers';
export { Lightbulb } from './Lightbulb';
export { Linkedin } from './Linkedin';
export { Loader2 } from './Loader2';
export { Lock } from './Lock';
export { Mail } from './Mail';
export { MailCheck } from './MailCheck';
export { MapPin } from './MapPin';
export { Menu } from './Menu';
export { PackageCheck } from './PackageCheck';
export { Phone } from './Phone';
export { Quote } from './Quote';
export { RefreshCw } from './RefreshCw';
export { Scale } from './Scale';
export { Search } from './Search';
export { Send } from './Send';
export { ShieldCheck } from './ShieldCheck';
export { Sliders } from './Sliders';
export { SlidersHorizontal } from './SlidersHorizontal';
export { Sparkles } from './Sparkles';
export { Star } from './Star';
export { Target } from './Target';
export { TrendingUp } from './TrendingUp';
export { User } from './User';
export { Users } from './Users';
export { Video } from './Video';
export { Workflow } from './Workflow';
export { X } from './X';
export { XCircle } from './XCircle';
export { Zap } from './Zap';

export { Icon } from './Icon';
export type { IconName } from './Icon';
